DROP TABLE IF EXISTS PostCategory;
DROP TABLE IF EXISTS PostRead;
DROP TABLE IF EXISTS Comment;
DROP TABLE IF EXISTS MailingListEntry;
DROP TABLE IF EXISTS d1_migrations;
DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS User;
